[Feat/#109] API 중간 점검 반영
TripMingle/Back-End-Application pull request #29
Opened 2024-06-20 06:49 UTC by min9yu98

### Issue Link

- close #109

### 핵심 내용

<img width="455" alt="스크린샷 2024-06-20 오후 3 49 16" src="https://github.com/TripMingle/Back-End/assets/76439068/7819122d-ef41-4a8c-b953-7691b55bc87d">

### 스크린샷 (선택)
-

### 전달 사항 (선택)

-

2024-06-20 11:54 UTC, thdgustjd1 requested changes
확인부탁드립니다.

2024-06-20 11:54 UTC, thdgustjd1 commented on src/main/java/com/example/tripmingle/application/service/PostingCommentService.java
> +        List<PostingComment> postingComments = postingCommentPersistPort.getPostingCommentsByPostingId(postingId);
이미 지워진 posting이라 null point exception이 발생할 것 같습니다. 로직 수정 부탁드립니다.

2024-06-21 00:05 UTC, thdgustjd1 approved these changes
확인하였습니다

2024-06-21 00:05 UTC, thdgustjd1 commented on src/main/java/com/example/tripmingle/application/facadeService/PostingFacadeService.java
>          postingLikesService.deletePostingWithPostingLikes(postingId);
메서드명이 deletePostingCommentsWithPosting 이 아닌 이유가 있는지 궁금합니다

2024-06-21 00:24 UTC, min9yu98 commented on src/main/java/com/example/tripmingle/application/service/PostingCommentService.java
> +        List<PostingComment> postingComments = postingCommentPersistPort.getPostingCommentsByPostingId(postingId);
반영했습니다.

2024-06-21 00:27 UTC, min9yu98 commented on src/main/java/com/example/tripmingle/application/facadeService/PostingFacadeService.java
>          postingLikesService.deletePostingWithPostingLikes(postingId);
반영했습니다.

2024-06-21 00:28 UTC, merged